ncov19-us/front-end

pages/desktop.py

put all chart and map into card.  
move all chart titles to div only with classname

han: app: 

---

assets/css/main.css
pages/about.py
pages/mobile_about.py

updated about page on web/mobile - social links and styling is responsive

Anisha css

---

components/daily_stats.py
components/daily_stats_mobile.py
pages/desktop.py

daily stats at the top now displaying data according to the state or us.
fixed api calls.

han: app: daily stats callback

---

components/__init__.py
components/column_stats.py
components/column_stats_mobile.py
components/daily_stats.py
components/daily_stats_mobile.py
components/twitter_feed.py
pages/desktop.py
pages/mobile.py
utils/settings.py

Migrated to the API Version 0.1.1 on staging.
Added callback to top bar. Desktop top bar now display the stats from the selected state.
Added callback to mobile top bar. Mobile top bar now display the stats from the selected state.

Desktop and Mobile Top Bars

---

pages/nav.py

+ Added  2 links  as temporary material to  fill up navBar
-> links are  to CDC & WHO covid19 resources

+ Added additional links to nav

---

components/column_stats.py
components/column_stats_mobile.py
components/confirmed_cases_chart.py
components/infection_trajectory_chart.py
components/scatter_mapbox.py
pages/nav.py
utils/settings.py

- All /county calls now have fields lower case with '_' instead of title case w/ ' '.
- please use pd.DataFrame.from_records to parse responses.

Han: changed API calls to accommodate to new API schema validation format

---

components/news_feed.py

fixed news feed from using read_json to from_records to accommodate new endpoint schema enforcement.

han: app: news feed fix.

---

pages/mobile_nav.py
pages/nav.py

Didnt notice the mobile nav.
added (temp) nav links to mobile nav

+ Added (Temp) Links to CDC & WHO to mobile Nav

---

assets/css/desktop.css
pages/nav.py

Added new Nav buttons,
Matched weight and size to figma.
***Links need to be added to nav buttons***
Co-authored-by: Michael <michael.chrupcala@gmail.com>
Co-authored-by: Hanchung Lee <kein520@yahoo.com>

Updated Nav bar

---

assets/css/desktop.css

Reduced spacing between  "Covid19" & "Track"
decreased height of navbar
Co-authored-by: Michael <michael.chrupcala@gmail.com>
Co-authored-by: Daniel F <trtld2@gmail.com>

+ adjustments made to nav

---

assets/css/mobile.css

Card Backs  removed
Co-authored-by: Michael <michael.chrupcala@gmail.com>

Mobile State bar now fixed,

---

assets/css/mobile.css
layout/mobile_layout.py
pages/mobile.py

styled mobile top dropdown menu
styled map tabs to show max content

Mobile top styling

---

assets/css/desktop.css

+ Made custom scroll bar

---

assets/css/desktop.css
components/cases_chart.py
components/daily_stats.py
components/deaths_chart.py
components/infection_trajectory_chart.py
components/new_infection_trajectory_chart.py
components/scatter_mapbox.py
components/stats_table.py
components/twitter_feed.py
pages/desktop.py
pages/mobile.py

components/: added del and gc logic, added caching. 
desktop.py: added comma styling for stats table
mobile.py: added comma styling for stats table

han: app: components/: added del and gc logic, added caching. 

---

assets/css/mobile.css
pages/mobile_nav.py
pages/nav.py

`mobile_nav.py`: added links to home, WHO, CDC
`nav.py`: added links to WHO, CDC. 
`mobile.css`: triaged the drop down :hamburger:

han: :top: fix, added :link:, :mobile_phone_off: :hamburger: fix.

---

components/cases_chart.py
components/daily_stats.py
components/daily_stats_mobile.py
components/deaths_chart.py
components/new_infection_trajectory_chart.py
components/news_feed.py
components/scatter_mapbox.py
components/twitter_feed.py
pages/desktop.py
pages/mobile.py

`desktop.py`, `mobile.py`: made newsfeed default and swapped position of news feed and twitter feed
`components/`: added `del` and `gc.collect()` for to improve memory performance.

han: :zap: memory optimization, :lipstick: swapped twitter and news feed position

---

assets/css/common.css
assets/css/desktop.css
assets/css/mobile.css
pages/desktop.py
pages/mobile.py

- dropdown menu styling
- desktop responsiveness
- mobile font sizes
- fixing mobile chart padding
- fixed tabs with messed up styling from news/twitter switch

liz: derek: css changes on web and mobile

---

app.py
components/daily_stats.py
components/stats_table.py
run.py
static/robots.txt

:arts: 
- `app.py`: added statics folder for flask server
- `run.py`: added flask route to `robots.txt`
- added `statics/` folder and added `statics/robots.txt`

:arts: Robot 

---

components/new_infection_trajectory_chart.py
pages/desktop.py
pages/mobile.py

Updated trajectory chart and subtitles to start when each state/country has 1 case per 100,000 people

Country chart

---

run.py
static/robots.txt

Changes:
`run.py`: commented out resources route. 
`robots.txt`: added crawl-delay 5 for bingbot

han: removed /resources route and added crawl-delay for bot.

---

assets/css/desktop.css
pages/desktop.py

Fixed issue: Lato was not displaying for daily stats
- Replaced variables into the respective stats using font variables

+ Reset Daily Stats to lato font using variable

---

assets/css/desktop.css

What Changed ? e.g. Github Issues Title or Trello Card Title
- [x ] :art: CSS Styling fix
- [x ] Manually Functionality Testing
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts

style: font fixes and sidebar heights

---

Pipfile
Pipfile.lock

Updated pipefile.lock, and added tests dependencies

chore: pipfile updated

---

pages/nav.py

What Changed ? e.g. Github Issues Title or Trello Card Title

chore: removed-sms-btn

---

LICENSE
README.md

What Changed ? Just the README & LICENSE

chore: updating READMEs

---

assets/css/desktop.css
assets/css/mobile.css

What Changed ? e.g. Github Issues Title or Trello Card Title

style: minor styling fix on mobile to match desktop

---

assets/css/desktop.css
assets/css/mobile.css
pages/mobile_footer.py
pages/mobile_nav.py

What Changed ? 
- Mobile navbar w/ SMS link
- Switched copyright and gihub icon on mobile to match desktop order
- Removed duplicate application of css on mobile navbar

style: fixed mobile navbar styling, added get sms update button to mobile nav menu
